part of 'installer.dart';

extension InstallerPlatformAliasPart on Installer {
  Future<void> _applyPlatformInstructions(Component component) async {
    await _ensureConfigLoaded();
    await _platformService.applyInstructions(component, config: _cachedConfig);
  }

  void _reportPostInstall(Component component) {
    _platformService.reportPostInstall(component);
  }

  Future<void> generateAliases() async {
    logger.progress('Regenerating app component aliases');
    await _ensureConfigLoaded();
    final config = _cachedConfig ?? const ShadcnConfig();
    final prefix = config.classPrefix;
    final componentsDir = Directory(
      _resolveProjectPath(p.join(_installPath(config), 'components')),
    );
    if (!componentsDir.existsSync()) {
      return;
    }

    final aliases = <String, InstallerAliasEntry>{};
    final imports = <String>{};
    final componentDirs = <String>{};
    for (final entity in componentsDir.listSync(recursive: true)) {
      if (entity is! Directory) {
        continue;
      }
      final name = p.basename(entity.path);
      final mainFile = File(p.join(entity.path, '$name.dart'));
      if (mainFile.existsSync()) {
        componentDirs.add(entity.path);
      }
    }

    // Scan in sorted order so duplicate ownership is deterministic: the
    // alphabetically first export wins and later exports hide the name.
    final sortedDirs = componentDirs.toList()..sort();
    final declarationOwners = <String, String>{};
    final exportHides = <String, Set<String>>{};
    final duplicateOwners = <String, Set<String>>{};
    for (final dirPath in sortedDirs) {
      final componentDir = Directory(dirPath);
      final componentName = p.basename(componentDir.path);
      final mainFile = File(p.join(componentDir.path, '$componentName.dart'));
      if (!mainFile.existsSync()) {
        continue;
      }
      final relativeDir = p.relative(
        componentDir.path,
        from: p.join(targetDir, _installPath(config)),
      );
      final importPath =
          p.join(relativeDir, '$componentName.dart').replaceAll('\\', '/');
      imports.add(importPath);
      // Scan the whole library: the main file plus its parts plus every
      // relatively exported file (transitively). Components like button
      // export their implementation instead of part-ing it, so a parts-only
      // scan misses declarations such as IconButton/TextButton and the
      // barrel silently reintroduces ambiguous imports.
      final scan = _scanComponentLibrary(
        componentDirPath: componentDir.path,
        mainFileName: '$componentName.dart',
      );
      for (final entry in scan.declarations.entries) {
        final className = entry.key;
        final typeParams = entry.value;
        if (typeParams != null) {
          aliases.putIfAbsent(
            className,
            () => InstallerAliasEntry(className, typeParams),
          );
        } else if (!aliases.containsKey(className)) {
          aliases[className] = InstallerAliasEntry(className, null);
        }
      }
      // Track every public declaration (class, enum, mixin, typedef). When
      // two component libraries declare the same name, exporting both
      // produces duplicate-symbol errors for barrel importers, so the later
      // export hides the name. This covers cases like form/autocomplete vs
      // form/text_field both declaring AutoComplete.
      for (final declaration in scan.declarations.keys) {
        final owner = declarationOwners[declaration];
        if (owner == null) {
          declarationOwners[declaration] = importPath;
        } else if (owner != importPath) {
          exportHides
              .putIfAbsent(importPath, () => <String>{})
              .add(declaration);
          duplicateOwners
              .putIfAbsent(declaration, () => <String>{})
              .addAll([owner, importPath]);
        }
      }
      // Component top-level functions colliding with material (e.g. the
      // dialog library's showDialog vs material's showDialog) get the same
      // treatment: hide them on the component export so the barrel stays
      // unambiguous. Material keeps the name.
      for (final function in scan.materialFunctions) {
        exportHides.putIfAbsent(importPath, () => <String>{}).add(function);
        duplicateOwners.putIfAbsent(function, () => <String>{}).addAll(
          ['package:flutter/material.dart', importPath],
        );
      }
    }
    if (duplicateOwners.isNotEmpty) {
      final details = duplicateOwners.entries.toList()
        ..sort((a, b) => a.key.compareTo(b.key));
      for (final entry in details) {
        final owners = entry.value.toList()..sort();
        logger.warn(
          'Duplicate declaration "${entry.key}" exported by '
          '${owners.join(' and ')}; hiding it on later exports in '
          'app_components.dart.',
        );
      }
    }

    final output = StringBuffer()
      ..writeln('// Generated by flutter_shadcn. Do not edit by hand.')
      ..writeln('');
    final hiddenMaterialNames = _materialNamesToHide(
      aliases.values.map((entry) => entry.className),
    );
    if (hiddenMaterialNames.isNotEmpty) {
      output.writeln("export 'package:flutter/material.dart' hide");
      for (var i = 0; i < hiddenMaterialNames.length; i += 1) {
        final suffix = i == hiddenMaterialNames.length - 1 ? ';' : ',';
        output.writeln('    ${hiddenMaterialNames[i]}$suffix');
      }
      output.writeln('');
    }
    final sortedImports = imports.toList()..sort();
    for (final importPath in sortedImports) {
      final hides = (exportHides[importPath]?.toList() ?? <String>[])..sort();
      if (hides.isEmpty) {
        output.writeln("export '$importPath';");
      } else {
        // Trailing-combinator syntax matters: every name but the last gets a
        // comma and the statement ends with ';'. A missing comma here makes
        // Dart misparse every export that follows.
        output.writeln("export '$importPath' hide ${hides.join(', ')};");
      }
    }
    if (prefix != null && prefix.isNotEmpty) {
      output.writeln('');
      for (final importPath in sortedImports) {
        output.writeln("import '$importPath';");
      }
      output.writeln('');
      final aliasEntries = aliases.entries.toList()
        ..sort((a, b) => a.key.compareTo(b.key));
      for (final entry in aliasEntries) {
        final className = entry.value.className;
        final aliasName = '$prefix$className';
        final typeParams = entry.value.typeParams;
        if (typeParams == null || typeParams.isEmpty) {
          output.writeln('typedef $aliasName = $className;');
        } else {
          final typeArgs = _typeArgsFromParams(typeParams);
          output
              .writeln('typedef $aliasName$typeParams = $className$typeArgs;');
        }
      }
    }

    final outputFile = File(
      _resolveProjectPath(p.join(_installPath(config), 'app_components.dart')),
    );
    await outputFile.writeAsString(output.toString());
  }

  List<String> _materialNamesToHide(Iterable<String> installedNames) {
    // Candidate set: every public registry declaration known to collide with
    // the package:flutter export graph. Note material.dart re-exports
    // widgets.dart wholesale, so widgets-level names (Form, RadioGroup,
    // TableCell, Row, Column, Stack, ...) collide too. Audited against the
    // Flutter SDK's transitive material.dart export graph (588 files, 1349
    // names); legacy entries are kept so existing barrels never lose a hide.
    // Missing entries here surface as ambiguous-import errors in apps
    // importing both Flutter and the barrel (e.g. BadgeTheme), so keep this
    // list complete.
    const materialExports = <String>{
      'AboutDialog',
      'ActionChip',
      'AlertDialog',
      'AppBar',
      'BackButton',
      'Badge',
      'BadgeTheme',
      'BottomNavigationBar',
      'ButtonBar',
      'ButtonStyle',
      'ButtonTheme',
      'Card',
      'CardTheme',
      'CarouselController',
      'Checkbox',
      'CheckboxTheme',
      'Chip',
      'ChipTheme',
      'CircularProgressIndicator',
      'Column',
      'DatePickerDialog',
      'DatePickerTheme',
      'DateTimeRange',
      'Dialog',
      'DialogRoute',
      'Divider',
      'DividerTheme',
      'Drawer',
      'DrawerTheme',
      'DropdownButton',
      'DropdownMenu',
      'DropdownMenuTheme',
      'ElevatedButton',
      'ElevatedButtonTheme',
      'ErrorWidgetBuilder',
      'Expanded',
      'Flex',
      'Flexible',
      'FloatingActionButton',
      'Form',
      'FormField',
      'FormState',
      'Icon',
      'IconButton',
      'IconButtonTheme',
      'LinearProgressIndicator',
      'ListTile',
      'MenuBar',
      'MenuButtonTheme',
      'MenuTheme',
      'NavigationBar',
      'NavigationBarTheme',
      'NavigationRail',
      'OutlinedButton',
      'OutlinedButtonTheme',
      'PopupMenuButton',
      'Positioned',
      'ProgressIndicator',
      'Radio',
      'RadioGroup',
      'RadioTheme',
      'Row',
      'Scaffold',
      'ScaffoldState',
      'Scrollbar',
      'ScrollbarTheme',
      'SelectableText',
      'Slider',
      'Stack',
      'Step',
      'StepState',
      'Stepper',
      'StepperType',
      'Switch',
      'SwitchTheme',
      'Tab',
      'TabBar',
      'Table',
      'TableCell',
      'TableRow',
      'Text',
      'TextButton',
      'TextButtonTheme',
      'TextField',
      'TimePickerDialog',
      'TimePickerTheme',
      'Tooltip',
      'TooltipTheme',
      'VerticalDivider',
      'showDialog',
    };
    final installedSet = installedNames.toSet();
    return materialExports.where((name) => installedSet.contains(name)).toList()
      ..sort();
  }
}

final _aliasEnumRegex = RegExp(
  r'^\s*enum\s+([A-Z]\w*)',
  multiLine: true,
);

final _aliasMixinRegex = RegExp(
  r'^\s*mixin\s+([A-Z]\w*)',
  multiLine: true,
);

final _aliasTypedefRegex = RegExp(
  r'^\s*typedef\s+([A-Z]\w*)\s*=',
  multiLine: true,
);

final _aliasExportRegex = RegExp(
  r'''export\s+['"]([^'"]+)['"]\s*([^;]*);''',
);

final _partOfRegex = RegExp(
  r'''^\s*part\s+of\s+(?:['"]([^'"]+)['"]\s*;|[A-Za-z_]\w*(?:\s*\.\s*[A-Za-z_]\w*)*\s*;)''',
  multiLine: true,
);

/// Whether the given file's declarations belong to the scanned library: true
/// for the main file and for files without a `part of` directive, and true
/// for `part of` files whose target resolves to the scanned main file.
bool _belongsToLibrary({
  required String content,
  required String fileDir,
  required String mainPath,
  required bool isMainFile,
}) {
  if (isMainFile) {
    return true;
  }
  final match = _partOfRegex.firstMatch(content);
  if (match == null) {
    return true;
  }
  final target = match.group(1);
  if (target == null || target.isEmpty) {
    // `part of LibraryName;` (named style): the target cannot be resolved
    // to this library, so do not attribute its declarations here.
    return false;
  }
  if (!_isRelativeRef(target)) {
    return false;
  }
  final resolved = p.normalize(p.join(fileDir, target));
  return resolved == mainPath;
}

/// Top-level functions exported by package:flutter/material.dart that a
/// component library may redeclare (today only showDialog).
const _aliasMaterialFunctions = <String>{
  'showDialog',
};

/// A library file queued for scanning, with the show/hide filter accumulated
/// from the chain of export directives that led to it (null show = all
/// names visible).
class _PendingScan {
  final String dir;
  final String path;
  final String content;
  final Set<String>? show;
  final Set<String> hide;

  const _PendingScan({
    required this.dir,
    required this.path,
    required this.content,
    required this.show,
    required this.hide,
  });
}

class _LibraryScan {
  /// Public declaration name -> class type parameters (null for
  /// enum/mixin/typedef or classes without type parameters... note: classes
  /// store their type parameter string, which may itself be null).
  final Map<String, String?> declarations;

  /// Declared top-level functions colliding with known material exports.
  final Set<String> materialFunctions;

  const _LibraryScan({
    required this.declarations,
    required this.materialFunctions,
  });
}

/// Collects every public declaration of a component library: the main file,
/// its parts, and every relatively exported file (transitively). Files that
/// are `part of` another library contribute nothing \u2014 their declarations
/// belong to that other library. Export show/hide combinators are honored so
/// hidden names are never attributed to the component.
_LibraryScan _scanComponentLibrary({
  required String componentDirPath,
  required String mainFileName,
}) {
  final declarations = <String, String?>{};
  final materialFunctions = <String>{};
  final seen = <String>{};
  final mainPath = p.normalize(p.join(componentDirPath, mainFileName));
  final mainFile = File(mainPath);
  if (!mainFile.existsSync()) {
    return _LibraryScan(
      declarations: declarations,
      materialFunctions: materialFunctions,
    );
  }
  final pending = <_PendingScan>[
    _PendingScan(
      dir: componentDirPath,
      path: mainPath,
      content: mainFile.readAsStringSync(),
      show: null,
      hide: const {},
    ),
  ];
  while (pending.isNotEmpty) {
    final current = pending.removeLast();
    if (!seen.add(current.path)) {
      continue;
    }
    final content = current.content;
    // A `part of` file only contributes its declarations when it belongs to
    // the library being scanned (its target resolves to the main file).
    // Otherwise the file belongs to a different library (e.g. a preview
    // part file) and its names must not be attributed here. References are
    // still followed so nothing reachable is missed.
    final belongsToLibrary = _belongsToLibrary(
      content: content,
      fileDir: current.dir,
      mainPath: mainPath,
      isMainFile: current.path == mainPath,
    );
    if (belongsToLibrary) {
      for (final match in _classRegex.allMatches(content)) {
        final name = match.group(2);
        if (name == null ||
            name.startsWith('_') ||
            !_combinatorVisible(name, current.show, current.hide)) {
          continue;
        }
        declarations.putIfAbsent(name, () => match.group(3));
      }
      for (final match in _aliasEnumRegex.allMatches(content)) {
        final name = match.group(1);
        if (name != null &&
            !name.startsWith('_') &&
            _combinatorVisible(name, current.show, current.hide)) {
          declarations.putIfAbsent(name, () => null);
        }
      }
      for (final match in _aliasMixinRegex.allMatches(content)) {
        final name = match.group(1);
        if (name != null &&
            !name.startsWith('_') &&
            _combinatorVisible(name, current.show, current.hide)) {
          declarations.putIfAbsent(name, () => null);
        }
      }
      for (final match in _aliasTypedefRegex.allMatches(content)) {
        final name = match.group(1);
        if (name != null &&
            !name.startsWith('_') &&
            _combinatorVisible(name, current.show, current.hide)) {
          declarations.putIfAbsent(name, () => null);
        }
      }
      for (final function in _materialFunctionDeclarations([content])) {
        if (_combinatorVisible(function, current.show, current.hide)) {
          materialFunctions.add(function);
        }
      }
    }
    for (final part in _partRegex.allMatches(content)) {
      final ref = part.group(1);
      if (ref == null || !_isRelativeRef(ref)) {
        continue;
      }
      final resolved = p.normalize(p.join(current.dir, ref));
      final file = File(resolved);
      if (!file.existsSync()) {
        continue;
      }
      pending.add(
        _PendingScan(
          dir: p.dirname(resolved),
          path: resolved,
          content: file.readAsStringSync(),
          show: current.show,
          hide: current.hide,
        ),
      );
    }
    for (final export in _aliasExportRegex.allMatches(content)) {
      final ref = export.group(1);
      if (ref == null || !_isRelativeRef(ref)) {
        continue;
      }
      final resolved = p.normalize(p.join(current.dir, ref));
      final file = File(resolved);
      if (!file.existsSync()) {
        continue;
      }
      final combinators = export.group(2) ?? '';
      pending.add(
        _PendingScan(
          dir: p.dirname(resolved),
          path: resolved,
          content: file.readAsStringSync(),
          show: _intersectShow(current.show, _parseShow(combinators)),
          hide: {...current.hide, ..._parseHide(combinators)},
        ),
      );
    }
  }
  return _LibraryScan(
    declarations: declarations,
    materialFunctions: materialFunctions,
  );
}

bool _isRelativeRef(String ref) {
  return !ref.startsWith('package:') &&
      !ref.startsWith('dart:') &&
      !ref.contains('://');
}

bool _combinatorVisible(String name, Set<String>? show, Set<String> hide) {
  if (hide.contains(name)) {
    return false;
  }
  return show == null || show.contains(name);
}

Set<String>? _intersectShow(Set<String>? parent, Set<String>? child) {
  if (parent == null) {
    return child;
  }
  if (child == null) {
    return parent;
  }
  return parent.intersection(child);
}

Set<String> _parseCombinatorNames(String combinators, String keyword) {
  final match = RegExp(
    '\\b$keyword\\s+([A-Za-z_]\\w*(?:\\s*,\\s*[A-Za-z_]\\w*)*)',
  ).firstMatch(combinators);
  if (match == null) {
    return const {};
  }
  return match
      .group(1)!
      .split(',')
      .map((entry) => entry.trim())
      .where((entry) => entry.isNotEmpty)
      .toSet();
}

Set<String>? _parseShow(String combinators) {
  final names = _parseCombinatorNames(combinators, 'show');
  // Distinguish "no show clause" (null = everything visible) from an
  // unparseable one by re-checking for the keyword.
  if (names.isEmpty && !combinators.contains(RegExp(r'\bshow\b'))) {
    return null;
  }
  return names;
}

Set<String> _parseHide(String combinators) {
  return _parseCombinatorNames(combinators, 'hide');
}

/// Finds declarations of known material top-level functions in the given
/// file contents, ignoring comment lines so doc references such as
/// "use [showDialog] instead" are not mistaken for declarations.
Set<String> _materialFunctionDeclarations(List<String> contents) {
  final names = <String>{};
  for (final content in contents) {
    for (final line in content.split('\n')) {
      final trimmed = line.trimLeft();
      if (trimmed.startsWith('//') ||
          trimmed.startsWith('*') ||
          trimmed.startsWith('/*')) {
        continue;
      }
      for (final function in _aliasMaterialFunctions) {
        final match = RegExp(
          '\\b$function\\s*(<[^>]*>)?\\s*\\(',
        ).firstMatch(line);
        if (match == null) {
          continue;
        }
        // The text before the name must look like a return type, not a call
        // site: it must contain a type word, and must not be an argument
        // position, assignment, await or return (e.g. `showDialog(` as a
        // bare call, `await showDialog(`, `foo(showDialog)`).
        final prefix = line.substring(0, match.start);
        if (!RegExp(r'\w').hasMatch(prefix) ||
            prefix.contains('(') ||
            prefix.contains('=') ||
            RegExp(r'\b(await|return|yield|assert)\b').hasMatch(prefix)) {
          continue;
        }
        names.add(function);
      }
    }
  }
  return names;
}
