import 'dart:io';

import 'package:flutter_shadcn_cli/src/application/services/installer/installer_alias_entry.dart';
import 'package:flutter_shadcn_cli/src/infrastructure/resolver/v1/project_path_guard.dart';
import 'package:path/path.dart' as p;

class InstallerAliasGeneratorService {
  InstallerAliasGeneratorService({
    required this.targetDir,
  });

  final String targetDir;

  Future<void> generateAliases({
    required String installPath,
    required String? classPrefix,
  }) async {
    final prefix = classPrefix;
    if (prefix == null || prefix.isEmpty) {
      return;
    }
    final componentsDir = Directory(
      _resolveProjectPath(p.join(installPath, 'components')),
    );
    if (!componentsDir.existsSync()) {
      return;
    }

    final aliases = <String, InstallerAliasEntry>{};
    final imports = <String>{};
    final componentDirs = <String>{};
    for (final entity in componentsDir.listSync(recursive: true)) {
      if (entity is! Directory) {
        continue;
      }
      final name = p.basename(entity.path);
      final mainFile = File(p.join(entity.path, '$name.dart'));
      if (mainFile.existsSync()) {
        componentDirs.add(entity.path);
      }
    }

    for (final dirPath in componentDirs) {
      final componentDir = Directory(dirPath);
      final componentName = p.basename(componentDir.path);
      final mainFile = File(p.join(componentDir.path, '$componentName.dart'));
      if (!mainFile.existsSync()) {
        continue;
      }
      final relativeDir = p.relative(
        componentDir.path,
        from: p.join(targetDir, installPath),
      );
      final importPath =
          p.join(relativeDir, '$componentName.dart').replaceAll('\\', '/');
      imports.add(importPath);
      final contents = <String>[];
      final mainContent = mainFile.readAsStringSync();
      contents.add(mainContent);
      for (final part in _partRegex.allMatches(mainContent)) {
        final partPath = part.group(1);
        if (partPath == null) {
          continue;
        }
        final partFile = File(p.join(componentDir.path, partPath));
        if (partFile.existsSync()) {
          contents.add(partFile.readAsStringSync());
        }
      }
      final matches =
          contents.expand((content) => _classRegex.allMatches(content));
      for (final match in matches) {
        final className = match.group(2);
        if (className == null || className.startsWith('_')) {
          continue;
        }
        final typeParams = match.group(3);
        final aliasName = '$prefix$className';
        aliases.putIfAbsent(
          aliasName,
          () => InstallerAliasEntry(className, typeParams),
        );
      }
    }

    final output = StringBuffer()
      ..writeln('// Generated by flutter_shadcn. Do not edit by hand.')
      ..writeln('library app_components;')
      ..writeln('');
    for (final importPath in imports.toList()..sort()) {
      output.writeln("import '$importPath';");
    }
    output.writeln('');
    final aliasEntries = aliases.entries.toList()
      ..sort((a, b) => a.key.compareTo(b.key));
    for (final entry in aliasEntries) {
      final aliasName = entry.key;
      final className = entry.value.className;
      final typeParams = entry.value.typeParams;
      if (typeParams == null || typeParams.isEmpty) {
        output.writeln('typedef $aliasName = $className;');
      } else {
        final typeArgs = _typeArgsFromParams(typeParams);
        output.writeln('typedef $aliasName$typeParams = $className$typeArgs;');
      }
    }

    final outputFile = File(
      _resolveProjectPath(p.join(installPath, 'app_components.dart')),
    );
    await outputFile.writeAsString(output.toString());
  }

  String _resolveProjectPath(String relativePath) {
    return ProjectPathGuard.resolveSafeWritePath(
      projectRoot: targetDir,
      destinationRelativePath: relativePath,
    );
  }

  String _typeArgsFromParams(String params) {
    final trimmed = params.replaceAll('<', '').replaceAll('>', '');
    final parts = trimmed.split(',');
    final args = <String>[];
    for (final part in parts) {
      final token = part.trim().split(' ').first;
      if (token.isNotEmpty) {
        args.add(token);
      }
    }
    return '<${args.join(', ')}>';
  }
}

final _classRegex = RegExp(
  r'^\s*(abstract\s+)?class\s+([A-Z]\w*)(\s*<[^>{}]+>)?',
  multiLine: true,
);

final _partRegex = RegExp(r'''part\s+['"]([^'"]+)['"];''');
